ktor:
  development: false
  application:
    modules:
      - xyz.avdt.ApplicationKt.module
  deployment:
    port: "$PORT:8080"
    database:
      host: "$DB_HOST:0.0.0.0"
      port: "$DB_PORT:5432"
      name: "$DB_NAME:shrtkt"
      user: "$DB_USER:postgres"
      password: "$DB_PASSWORD:password"
    redis:
      url: "$REDIS_URL:redis://default@0.0.0.0:6379"
    watch:
      - classes
      - resources